# Generated by Django 5.2.15 on 2026-06-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profile_avatar',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
