# Generated by Django 5.2.15 on 2026-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='CLSIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ kết quả'), ('completed', 'Đã có kết quả')], default='pending', max_length=20)),
                ('result', models.TextField(blank=True, default='')),
                ('result_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chỉ định CLS',
                'verbose_name_plural': 'Chỉ định CLS',
                'db_table': 'cls_indication',
            },
        ),
        migrations.CreateModel(
            name='CLSService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Dịch vụ CLS',
                'verbose_name_plural': 'Dịch vụ CLS',
                'db_table': 'cls_service',
            },
        ),
        migrations.CreateModel(
            name='ExaminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('medical_history', models.TextField(blank=True, default='')),
                ('family_history', models.TextField(blank=True, default='')),
                ('pulse', models.CharField(blank=True, default='', max_length=20)),
                ('temperature', models.CharField(blank=True, default='', max_length=20)),
                ('blood_pressure', models.CharField(blank=True, default='', max_length=20)),
                ('weight', models.CharField(blank=True, default='', max_length=20)),
                ('health_status', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Phiếu khám',
                'verbose_name_plural': 'Phiếu khám',
                'db_table': 'examination_record',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Male', 'Nam'), ('Female', 'Nữ')], default='Male', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('cccd', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('ward', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('insurance', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hồ sơ bệnh nhân',
                'verbose_name_plural': 'Hồ sơ bệnh nhân',
                'db_table': 'patient_profile',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Trạng thái',
                'verbose_name_plural': 'Trạng thái',
                'db_table': 'appointment_status',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Giờ',
                'verbose_name_plural': 'Giờ',
                'db_table': 'time_slot',
            },
        ),
    ]
