# Generated by Django 5.2.15 on 2026-06-21 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctors'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patients'),
        ),
        migrations.AddField(
            model_name='clsindication',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clsindication',
            name='cls_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.clsservice'),
        ),
        migrations.AddField(
            model_name='examinationrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.appointment'),
        ),
        migrations.AddField(
            model_name='examinationrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='users.doctors'),
        ),
        migrations.AddField(
            model_name='clsindication',
            name='examination_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cls_indications', to='patients.examinationrecord'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationrecord',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.status'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.time'),
        ),
    ]
