# Generated by Django 5.2.15 on 2026-06-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
