# Generated by Django 5.2.15 on 2026-06-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_appointment_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
